language: haskell

install:
  - sudo apt-get update -qq
  - cabal update
  - cabal install --only-dependencies --enable-tests

script:
  - cabal install && cabal configure --enable-tests && cabal build
  - ./dist/build/regression-suite/regression-suite
